version: '3.8'

services:
  chill-movie-app:
    image: ardidafa/chill-movie-apps:latest
    container_name: chill-movie-app
    restart: unless-stopped
    ports:
      - "3000:80" # Ganti 80 di sini jika perlu, tetapi pastikan ini sesuai dengan pengaturan Nginx
    volumes:
      - ./nginx-cloudflare.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web

networks:
  web:
    driver: bridge
